#!/bin/sh
SCRIPTDIR=`dirname $0`
DATEYEAR=`date +%Y`
CREATION=`date "+%Y-%m-%d %H:%M:%S %z"`
if [[ $1 ]]; then
    FILETEXT="    $1\n    ~~~~~"
else
    FILETEXT=""
fi;
source $SCRIPTDIR/script_env

function pheadEcho {
    echo "#!/usr/bin/env python"
    echo "# -*- encoding: utf-8 -*-"
    echo "\"\"\"
$FILETEXT

    :created: $CREATION
    :copyright: (c) $DATEYEAR, $ENTITY
    :license: $LICENSE_DESC
\"\"\"
"
}

pheadEcho
